export const CHANGE_LOCALE = `CHANGE_LOCALE`

export const FETCH_USERS = `FETCH_USERS`
export const FETCH_USERS_SUCCESS = `FETCH_USERS_SUCCESS`
export const FETCH_USERS_FAILURE = `FETCH_USERS_FAILURE`
